name: Unit tests

on:
  push:
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - uses: cachix/install-nix-action@30
      - run: |
          nix profile install --accept-flake-config github:cachix/devenv
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          devenv test
          
