name: Unit tests

on:
  push:
  pull_request:

jobs:
  unittests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4      
      - uses: cachix/install-nix-action@v31.4.1
      - run: |
          nix profile install --accept-flake-config github:cachix/devenv
          export PYTHON_KEYRING_BACKEND=keyrings.alt.file.PlaintextKeyring
          devenv update
          devenv test
