name: Unit tests

on:
  push:
    branches:
      # we can only test the main branch until i can figure out
      # how to not use the GitHub URL in devenv.nix
      - main

jobs:
  unittests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - uses: DeterminateSystems/determinate-nix-action@main
      - run: |
          nix profile install --accept-flake-config github:cachix/devenv
          export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
          devenv test
          
